//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentingGown.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentingGownDB : DbContext
    {
        public RentingGownDB()
            : base("name=RentingGownDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Catgories> Catgories { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Gowns> Gowns { get; set; }
        public virtual DbSet<Renters> Renters { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<Sets> Sets { get; set; }
        public virtual DbSet<Tenants> Tenants { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Rents> Rents { get; set; }
    }
}
