//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentingGown.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int id { get; set; }
        public int id_tenant { get; set; }
        public int id_gown { get; set; }
        public Nullable<int> payment { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> is_payed { get; set; }
        public Nullable<bool> is_returned { get; set; }
    
        public virtual Gowns Gowns { get; set; }
        public virtual Gowns Gowns1 { get; set; }
        public virtual Tenants Tenants { get; set; }
        public virtual Tenants Tenants1 { get; set; }
    }
}
